version: '3.8'
services:
  postgres_db_security:
    container_name: postgres_db_security
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_security
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_security:/var/lib/postgresql/data
volumes:
  postgres_db_security:
    external: false